<a href="https://colab.research.google.com/github/HariPrasad017/IIP_AIMLTN_ASSESMENT/blob/main/Data_Prep_%26_Feature_Engineering_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step 1 — Understanding the Dataset

Alright, first I created a small dataset of passengers with details like gender, city, size, age, and fare.
Some of these are categorical, so I need to convert them into numbers before giving them to a machine learning model.

# Step 2 — Create the DataFrame

In [1]:
import pandas as pd

data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}

df = pd.DataFrame(data)
df

   Gender     City    Size  Age  Fare
0    Male   Mumbai   Small   25    15
1  Female    Delhi   Large   45   300
2  Female  Chennai  Medium   32    85
3    Male   Mumbai   Large   60   450
4  Female    Delhi   Small   28    20

# Task 1 — Categorical Encoding

My Approach
- Gender -> simple category -> Label Encoding
- City -> multiple categories -> One-Hot Encoding
- Size -> ordered category -> Custom Label Encoding

In [2]:
# Label Encoding for Gender
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})


# One-Hot Encoding for City (drop one column to avoid dummy variable trap)
df = pd.get_dummies(df, columns=['City'], drop_first=True)


# Label Encoding for Size with order
size_mapping = {'Small': 0, 'Medium': 1, 'Large': 2}
df['Size'] = df['Size'].map(size_mapping)

df

   Gender  Size  Age  Fare  City_Delhi  City_Mumbai
0       0     0   25    15       False         True
1       1     2   45   300        True        False
2       1     1   32    85       False        False
3       0     2   60   450       False         True
4       1     0   28    20        True        False

# Task 2 — Feature Scaling

## My Thought Process

I noticed that:

- Fare has a big outlier -> 450
- If I use StandardScaler, it might get affected by that outlier

So I’m using RobustScaler, because it handles outliers better using median and IQR.

# Scaling Implementation

In [3]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

df

   Gender  Size       Age      Fare  City_Delhi  City_Mumbai
0       0     0 -0.411765 -0.250000       False         True
1       1     2  0.764706  0.767857        True        False
2       1     1  0.000000  0.000000       False        False
3       0     2  1.647059  1.303571       False         True
4       1     0 -0.235294 -0.232143        True        False