<a href="https://colab.research.google.com/github/HariPrasad017/IIP_AIMLTN_ASSESMENT/blob/main/Ecommerce_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

Title:
E-commerce Sales Performance Analysis

Description

In this project, we analyze sales data from an e-commerce company to identify sales trends and top performers. Since the real database is unavailable, a synthetic dataset of 200 transactions is generated.

The analysis focuses on:

1. Sales performance by region

2. Transaction counts by product category

3. Performance comparison between salespersons

4. Multi-column grouping analysis

5. Custom aggregation functions

Using Pandas groupby operations, we generate summary reports to support management decision-making.

# Import Libraries

In [1]:
import pandas as pd
import random

Explanation

1. Pandas is used for data manipulation and analysis.

2. Random is used to generate synthetic sales data.

# Generate Synthetic Dataset

In [2]:
random.seed(42)

regions = ['North', 'South', 'East', 'West']
categories = ['Electronics', 'Clothing', 'Home & Garden', 'Sports', 'Books']
salespersons = ['Alice', 'Bob', 'Carol', 'David', 'Emma', 'Frank']

data = {
    'transaction_id': range(1001, 1201),
    'region': [random.choice(regions) for _ in range(200)],
    'category': [random.choice(categories) for _ in range(200)],
    'salesperson': [random.choice(salespersons) for _ in range(200)],
    'sales_amount': [round(random.uniform(50, 5000), 2) for _ in range(200)],
    'customer_id': [random.randint(5000, 5100) for _ in range(200)]
}

df = pd.DataFrame(data)

print(df.head(10))
print("\nDataset shape:", df.shape)

   transaction_id region     category salesperson  sales_amount  customer_id
0            1001  North  Electronics        Emma       4000.80         5075
1            1002  North        Books       Alice       3634.70         5084
2            1003   East  Electronics       David       4210.50         5025
3            1004  South  Electronics        Emma       4601.73         5054
4            1005  South     Clothing         Bob       4904.57         5014
5            1006  South     Clothing       Carol       2693.91         5069
6            1007  North       Sports       Alice       4539.30         5028
7            1008  North       Sports       Frank       2979.87         5082
8            1009   West       Sports       David       3331.85         5019
9            1010  North     Clothing       Alice        465.54         5034

Dataset shape: (200, 6)

Explanation

This code:

1. Defines possible values for:



*   Regions
*   Product Categories


*   Salespersons


2. Generates 200 random transactions

3. Creates a Pandas DataFrame

| Column         | Description            |
| -------------- | ---------------------- |
| transaction_id | unique transaction     |
| region         | sales region           |
| category       | product category       |
| salesperson    | employee who made sale |
| sales_amount   | transaction value      |
| customer_id    | customer identifier    |

# TASK 1: Basic Grouping and Aggregations

**Total Sales by** **Region**

In [3]:
regional_sales = df.groupby('region')['sales_amount'].sum().reset_index()

regional_sales = regional_sales.sort_values(by='sales_amount', ascending=False)

print("Total Sales by Region")
display(regional_sales)

Total Sales by Region

  region  sales_amount
2  South     158977.36
1  North     135181.16
3   West     109383.07
0   East      95189.81

Explanation

groupby('region') groups data by region.

sales_amount.sum() calculates total sales per region.

reset_index() converts the grouped result into a clean DataFrame.

sort_values() sorts regions from highest to lowest sales.

This helps identify the top-performing region.

# Transaction Count by Category

In [4]:
category_transactions = df.groupby('category')['transaction_id'].count().reset_index()

print("Transactions per Category")
display(category_transactions)

Transactions per Category

        category  transaction_id
0          Books              39
1       Clothing              42
2    Electronics              45
3  Home & Garden              43
4         Sports              31

Explanation

This calculates number of transactions per product category.

We use:

groupby('category')
count()

This shows which product categories are most popular.

# Average Sales per Salesperson

In [5]:
avg_salesperson_sales = df.groupby('salesperson')['sales_amount'].mean().reset_index()

print("Average Sales per Salesperson")
display(avg_salesperson_sales)

Average Sales per Salesperson

  salesperson  sales_amount
0       Alice   1998.432273
1         Bob   2554.919063
2       Carol   2454.368571
3       David   2743.036444
4        Emma   2493.457273
5       Frank   2464.135750

Explanation

This calculates the average transaction value for each salesperson.

mean() computes the average sales amount.

This helps evaluate salesperson performance.

# TASK 2: Multi-Column Grouping

**Sales by Region AND Category**

In [6]:
region_category_sales = df.groupby(['region', 'category'])['sales_amount'].sum().reset_index()

print("Sales by Region and Category")
display(region_category_sales)

Sales by Region and Category

   region       category  sales_amount
0    East          Books      20027.53
1    East       Clothing      19926.20
2    East    Electronics      22791.55
3    East  Home & Garden      15949.08
4    East         Sports      16495.45
5   North          Books      42592.53
6   North       Clothing      18959.06
7   North    Electronics      38889.84
8   North  Home & Garden      19344.48
9   North         Sports      15395.25
10  South          Books      21007.68
11  South       Clothing      50878.36
12  South    Electronics      39229.63
13  South  Home & Garden      22592.00
14  South         Sports      25269.69
15   West          Books      20359.41
16   West       Clothing      16548.81
17   West    Electronics      13553.27
18   West  Home & Garden      33069.36
19   West         Sports      25852.22

Explanation

This groups data using two columns simultaneously:

region
category

It shows which product categories perform best in each region.

Example insight:

1. Electronics may sell more in North

2. Clothing may sell more in South

# Multiple Aggregations for Salespersons

In [7]:
salesperson_performance = df.groupby('salesperson')['sales_amount'].agg(['sum', 'mean', 'count']).reset_index()

print("Salesperson Performance")
display(salesperson_performance)

Salesperson Performance

  salesperson        sum         mean  count
0       Alice   43965.51  1998.432273     22
1         Bob   81757.41  2554.919063     32
2       Carol   68722.32  2454.368571     28
3       David  123436.64  2743.036444     45
4        Emma   82284.09  2493.457273     33
5       Frank   98565.43  2464.135750     40

Explanation

The .agg() function allows multiple metrics at once.

Metrics calculated:

# Sort Salespersons by Total Sales

In [8]:
salesperson_performance = salesperson_performance.sort_values(by='sum', ascending=False)

print("Top Performing Salespersons")
display(salesperson_performance)

Top Performing Salespersons

  salesperson        sum         mean  count
3       David  123436.64  2743.036444     45
5       Frank   98565.43  2464.135750     40
4        Emma   82284.09  2493.457273     33
1         Bob   81757.41  2554.919063     32
2       Carol   68722.32  2454.368571     28
0       Alice   43965.51  1998.432273     22

Explanation

Sorting by sum identifies the top sales performer.

# Find Category with Maximum Revenue

In [9]:
category_sales = df.groupby('category')['sales_amount'].sum()

top_category = category_sales.idxmax()

print("Category with Maximum Revenue:", top_category)

Category with Maximum Revenue: Electronics

Explanation

idxmax() finds the index with highest value.

So it returns the category generating the most revenue.

# TASK 3: Custom Aggregation

**Define Custom** **Function**

In [10]:
def sales_range(x):
    return x.max() - x.min()

Explanation

This function calculates:

 sales range = maximum sale - minimum sale

It measures variation in sales amounts.

# Apply Custom Aggregation

In [11]:
region_analysis = df.groupby('region')['sales_amount'].agg(['sum','mean','min','max', sales_range]).reset_index()

print("Region Sales Analysis")
display(region_analysis)

Region Sales Analysis

  region        sum         mean     min      max  sales_range
0   East   95189.81  2213.716512  307.82  4758.46      4450.64
1  North  135181.16  2413.949286  110.71  4788.56      4677.85
2  South  158977.36  2789.076491  373.45  4983.33      4609.88
3   West  109383.07  2485.978864  203.60  4903.53      4699.93

# Final Sales Summary Report

In [12]:
final_report = df.groupby('region').agg({
    'sales_amount': ['sum', 'mean'],
    'customer_id': 'count'
}).reset_index()

print("Final Sales Summary Report")
display(final_report)

Final Sales Summary Report

  region sales_amount              customer_id
                  sum         mean       count
0   East     95189.81  2213.716512          43
1  North    135181.16  2413.949286          56
2  South    158977.36  2789.076491          57
3   West    109383.07  2485.978864          44

# Multi-Level Column Structure Explanation

When we use dictionary-based aggregation like:

df.groupby('region').agg({

'sales_amount':['sum','mean'],

'customer_id':'count'

})

Pandas creates multi-level column names.

| region | sales_amount | sales_amount | customer_id |
| ------ | ------------ | ------------ | ----------- |
|        | sum          | mean         | count       |

This happens because:

1. One column (sales_amount) has multiple aggregations

2. Pandas organizes them in hierarchical columns

This differs from single aggregation because:

Single aggregation produces one column only, while multi aggregation produces multiple statistical measures per column.

# Conclusion

This analysis demonstrates how Pandas grouping operations can be used to analyze sales data effectively. By applying groupby functions, multiple aggregations, and custom functions, we identified top-performing regions, categories, and salespersons.

The analysis also demonstrated the power of multi-column grouping and hierarchical aggregations for generating detailed business reports.

Such techniques are widely used in real-world data analytics and business intelligence systems.