<a href="https://colab.research.google.com/github/HariPrasad017/IIP_AIMLTN_ASSESMENT/blob/main/Hari_Prasad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

Title:
Data Merging and Lookup Operations with Pandas

Description:

This project demonstrates how to work with multiple datasets using the Python Pandas library. The tasks include handling missing values, performing different join operations, and implementing lookup techniques for efficient data retrieval.

Three datasets are used:

Students Dataset – Contains student personal information

Enrollments Dataset – Contains course enrollment details

Scores Dataset – Contains exam scores of students

The project also compares merge vs lookup operations and implements a custom automation function for joins.

# Import Libraries

In [2]:
import pandas as pd
import numpy as np

Explanation

Pandas is used for data manipulation and analysis. NumPy is used for numerical operations.

# Task 1 – Data Preparation

**Step 1: Create** **DataFrames**

In [3]:
students_data = {
    'student_id': [101, 102, 103, 104, 105, 106, 107],
    'name': ['Alice', 'Bob', None, 'David', 'Emma', 'Frank', 'Grace'],
    'email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', None, 'emma@email.com', 'frank@email.com', 'grace@email.com'],
    'city': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', None, 'Chennai', 'Delhi']
}

enrollments_data = {
    'student_id': [101, 102, 103, 105, 108, 109],
    'course_name': ['Python', 'Data Science', 'Python', 'Machine Learning', 'AI', 'Python'],
    'enrollment_date': ['2024-01-15', '2024-01-20', '2024-02-01', '2024-02-10', '2024-02-15', '2024-03-01']
}

scores_data = {
    'student_id': [101, 102, 104, 105, 106],
    'exam_score': [85, 92, 78, 88, 95]
}

students = pd.DataFrame(students_data)
enrollments = pd.DataFrame(enrollments_data)
scores = pd.DataFrame(scores_data)

print("Original Students DataFrame")
display(students)

Original Students DataFrame

   student_id   name              email       city
0         101  Alice    alice@email.com     Mumbai
1         102    Bob      bob@email.com      Delhi
2         103   None  charlie@email.com  Bangalore
3         104  David               None     Mumbai
4         105   Emma     emma@email.com       None
5         106  Frank    frank@email.com    Chennai
6         107  Grace    grace@email.com      Delhi

Explanation

This step converts dictionary data into Pandas DataFrames which makes the data easier to manipulate.

**Step 2: Null Value** **Analysis**

In [4]:
print("Null Value Analysis")

null_counts = students.isnull().sum()
null_percentage = (students.isnull().sum() / len(students)) * 100

for col in students.columns:
    print(f"Column: {col}, Nulls: {null_counts[col]} ({null_percentage[col]:.2f}%)")

Null Value Analysis
Column: student_id, Nulls: 0 (0.00%)
Column: name, Nulls: 1 (14.29%)
Column: email, Nulls: 1 (14.29%)
Column: city, Nulls: 1 (14.29%)

Explanation:

1. isnull() detects missing values.

2. sum() counts them.

3. Percentage helps understand how much data is missing.

# Step 3: Fill Missing City Values

In [5]:
students['city'] = students['city'].fillna('Unknown')

Explanation:

Missing values in city are replaced with "Unknown".

# Step 4: Drop Missing Names

In [6]:
students_clean = students.dropna(subset=['name'])

print("Cleaned Students DataFrame")
display(students_clean)

Cleaned Students DataFrame

   student_id   name            email     city
0         101  Alice  alice@email.com   Mumbai
1         102    Bob    bob@email.com    Delhi
3         104  David             None   Mumbai
4         105   Emma   emma@email.com  Unknown
5         106  Frank  frank@email.com  Chennai
6         107  Grace  grace@email.com    Delhi

Explanation:

1. Rows with missing names are removed.

2. Because student identity cannot be missing.

Final rows = 6 students

# Task 2 – Join Operations

**Inner** **Join**

In [8]:
inner_join = pd.merge(students_clean, enrollments, on='student_id', how='inner')

print("Inner Join Result")
display(inner_join)

print("Total rows:", len(inner_join))

Inner Join Result

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10

Total rows: 3

Explanation:

Inner join keeps only matching student_ids in both tables.

Result students:

101 Alice

102 Bob

105 Emma

Excluded students:

104, 106, 107

Reason:

They are not present in enrollments table.

# Left Join

In [9]:
left_join = pd.merge(students_clean, enrollments, on='student_id', how='left')

print("Left Join Result")
display(left_join)

print("Total rows:", len(left_join))

Left Join Result

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,104,David,None,Mumbai,NaN,NaN
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,106,Frank,frank@email.com,Chennai,NaN,NaN
5,107,Grace,grace@email.com,Delhi,NaN,NaN

Total rows: 6

Explanation:

Left join keeps all students, even if they are not enrolled.

Students with null course_name:

104, 106, 107

Reason:

They did not enroll in any course.

In [10]:
right_join = pd.merge(students_clean, enrollments, on='student_id', how='right')

print("Right Join Result")
display(right_join)

print("Total rows:", len(right_join))

Right Join Result

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,103,NaN,NaN,NaN,Python,2024-02-01
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,108,NaN,NaN,NaN,AI,2024-02-15
5,109,NaN,NaN,NaN,Python,2024-03-01

Total rows: 6

Explanation:

Right join keeps all enrollments.

Student IDs without names:

108, 109

Reason:

These IDs exist in enrollments but not in students dataset.

# Full Outer Join

In [11]:
outer_join = pd.merge(students_clean, enrollments, on='student_id', how='outer')

print("Outer Join Result")
display(outer_join)

print("Total rows:", len(outer_join))

Outer Join Result

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,103,NaN,NaN,NaN,Python,2024-02-01
3,104,David,None,Mumbai,NaN,NaN
4,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
5,106,Frank,frank@email.com,Chennai,NaN,NaN
6,107,Grace,grace@email.com,Delhi,NaN,NaN
7,108,NaN,NaN,NaN,AI,2024-02-15
8,109,NaN,NaN,NaN,Python,2024-03-01

Total rows: 9

Explanation:

Outer join keeps all rows from both tables.

# Rows with Missing Data

In [12]:
missing_rows = outer_join[(outer_join['name'].isnull()) | (outer_join['course_name'].isnull())]

display(missing_rows)

   student_id   name            email     city course_name enrollment_date
2         103    NaN              NaN      NaN      Python      2024-02-01
3         104  David             None   Mumbai         NaN             NaN
5         106  Frank  frank@email.com  Chennai         NaN             NaN
6         107  Grace  grace@email.com    Delhi         NaN             NaN
7         108    NaN              NaN      NaN          AI      2024-02-15
8         109    NaN              NaN      NaN      Python      2024-03-01

Explanation:

This shows students without courses OR enrollments without student data.

# Merge Indicator

In [13]:
outer_indicator = pd.merge(students_clean, enrollments, on='student_id', how='outer', indicator=True)

display(outer_indicator)

print("Merge Source Distribution")
print(outer_indicator['_merge'].value_counts())

,student_id,name,email,city,course_name,enrollment_date,_merge
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15,both
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20,both
2,103,NaN,NaN,NaN,Python,2024-02-01,right_only
3,104,David,None,Mumbai,NaN,NaN,left_only
4,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10,both
5,106,Frank,frank@email.com,Chennai,NaN,NaN,left_only
6,107,Grace,grace@email.com,Delhi,NaN,NaN,left_only
7,108,NaN,NaN,NaN,AI,2024-02-15,right_only
8,109,NaN,NaN,NaN,Python,2024-03-01,right_only

Merge Source Distribution
_merge
left_only     3
right_only    3
both          3
Name: count, dtype: int64

# Task 3 – Lookup Operation

**Dictionary** **Mapping**

In [14]:
score_dict = scores.set_index('student_id')['exam_score'].to_dict()

print(score_dict)

{101: 85, 102: 92, 104: 78, 105: 88, 106: 95}

Explanation:

Creates dictionary like:

{101:85,102:92,104:78,105:88,106:95}

**Add Scores using map()**

In [15]:
students_clean['exam_score'] = students_clean['student_id'].map(score_dict)

display(students_clean)

/tmp/ipykernel_770/889925960.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students_clean['exam_score'] = students_clean['student_id'].map(score_dict)

   student_id   name            email     city  exam_score
0         101  Alice  alice@email.com   Mumbai        85.0
1         102    Bob    bob@email.com    Delhi        92.0
3         104  David             None   Mumbai        78.0
4         105   Emma   emma@email.com  Unknown        88.0
5         106  Frank  frank@email.com  Chennai        95.0
6         107  Grace  grace@email.com    Delhi         NaN

Explanation:

.map() performs fast lookup using dictionary keys.

Students without scores get NaN.

# Merge Method

In [16]:
merge_scores = pd.merge(students_clean, scores, on='student_id', how='left')

display(merge_scores)

   student_id   name            email     city  exam_score_x  exam_score_y
0         101  Alice  alice@email.com   Mumbai          85.0          85.0
1         102    Bob    bob@email.com    Delhi          92.0          92.0
2         104  David             None   Mumbai          78.0          78.0
3         105   Emma   emma@email.com  Unknown          88.0          88.0
4         106  Frank  frank@email.com  Chennai          95.0          95.0
5         107  Grace  grace@email.com    Delhi           NaN           NaN

Explanation:

This performs the same operation using merge.

# Why map() is Faster

Write this in Markdown:

Lookup using .map() is faster than merge() when we only need to map one column because:

1. It uses dictionary-based lookup (O(1) time complexity)

2. It avoids creating a full join operation

3. It uses less memory

4. It is simpler when mapping one key to one value

Merge is better when combining multiple columns or complex datasets.

# Automation Function

In [17]:
def auto_merge(df1, df2, join_type, key_column):

    merged_df = pd.merge(df1, df2, on=key_column, how=join_type)

    result = {
        'result_df': merged_df,
        'row_count': len(merged_df),
        'join_type': join_type
    }

    return result

Explanation:

This function:

1. Accepts two dataframes

2. Accepts join type

3. Performs merge

4. Returns dictionary with results

# Test the Function

In [18]:
test_inner = auto_merge(students_clean, enrollments, 'inner', 'student_id')

print("Join Type:", test_inner['join_type'])
print("Rows:", test_inner['row_count'])

display(test_inner['result_df'])

Join Type: inner
Rows: 3

,student_id,name,email,city,exam_score,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,85.0,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,92.0,Data Science,2024-01-20
2,105,Emma,emma@email.com,Unknown,88.0,Machine Learning,2024-02-10

**Second Test**

In [19]:
test_left = auto_merge(students_clean, enrollments, 'left', 'student_id')

print("Join Type:", test_left['join_type'])
print("Rows:", test_left['row_count'])

display(test_left['result_df'])

Join Type: left
Rows: 6

,student_id,name,email,city,exam_score,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,85.0,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,92.0,Data Science,2024-01-20
2,104,David,None,Mumbai,78.0,NaN,NaN
3,105,Emma,emma@email.com,Unknown,88.0,Machine Learning,2024-02-10
4,106,Frank,frank@email.com,Chennai,95.0,NaN,NaN
5,107,Grace,grace@email.com,Delhi,NaN,NaN,NaN

# Conclusion

Example:

This project demonstrated how to perform data merging and lookup operations using Pandas. Different join techniques such as inner join, left join, right join, and outer join were implemented to combine datasets. Missing values were handled effectively, and lookup operations using .map() were compared with traditional merge operations. Finally, an automation function was created to simplify merging tasks.

These techniques are essential in real-world data analytics when working with multiple relational datasets.